- name: add apt keys
  apt_key: url={{ item.url }} state=present
  with_items: "{{ keys_url }}"
- name: add repos
  apt_repository: repo={{ item.url }} state=present update_cache=yes
  with_items: "{{ repos }}"
- name: install server
  apt: name={{ item }} state=present
  with_items:
          - kibana
          - nginx
  notify: 
          - start kibana
- name: configure nginx
  template: backup=yes  dest="/etc/nginx/sites-available/default" src={{ kibana_nginx_config }}
  notify:
        - restart nginx
  
