syntax enable  
filetype plugin on  
set number  

if v:progname =~? "evim"
  finish
endif
set nocompatible
set backspace=indent,eol,start
set nobackup		
set history=50		
set ruler		
set showcmd	
set incsearch	
set nu
syntax on
map Q gq
if &t_Co > 2 || has("gui_running")
endif
if has("autocmd")
  filetype plugin indent on
  augroup vimrcEx
  au!
  autocmd FileType text setlocal textwidth=78
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

  augroup END

else

  set autoindent		" always set autoindenting on
endif " has("autocmd")
